apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webapp.fullname" . }}-db-secret
type: Opaque
data:
  mysql-root-password: {{ .Values.db.rootPassword | b64enc }}
  mysql-password: {{ .Values.db.password | b64enc }}